name       : powerline-fonts
version    : 2015.12.04
release    : 3
source     :
    - https://github.com/powerline/fonts/archive/2015-12-04.tar.gz : 3a0b73abca6334b5e6bddefab67f6eb1b2fac1231817d95fc79126c8998c4844
license    :
    - Apache-2.0
    - DejaVu Fonts License
    - Freeware
    - MIT
    - OFL-1.0
    - OFL-1.1
    - Ubuntu Font License
    - Copyright
component  : desktop.font
summary    : Powerline Font Pack
description: |
    Powerline Fonts:
    Anonymice Powerline
    Arimo Powerline
    Cousine Powerline
    Droid Sans Mono for Powerline
    Droid Sans Mono Slashed for Powerline
    Droid Sans Mono Dotted for Powerline
    Inconsolata for Powerline
    Inconsolata-dz for Powerline
    Inconsolata-g for Powerline
    Literation Mono Powerline
    Meslo for Powerline
    Roboto for Powerline
    Sauce Code Powerline
    Symbol Neu Powerline
    Terminess Powerline
    Tinos Powerline
    Fura Powerline
install    : |
    rm -r install.sh install.ps1 samples
    mkdir -p $installdir/usr/share/fonts/powerline
    cp -r * $installdir/usr/share/fonts/powerline
