name       : powerline-fonts
version    : 0.1
release    : 1
source     :
    - http://solus-us.tk/powerline-fonts-0.1.tar.gz : ef1c2fc9fd8d6c33576dcddc59787ea58b01e5af30755947b4ea400cd021f700
license    :
    - Apache-2.0
    - OFL-1.0
    - OFL-1.1
summary    : Powerline Font Pack
description: |
    Powerline Fonts:
    Anonymice Powerline
    Arimo Powerline
    Cousine Powerline
    Droid Sans Mono for Powerline
    Droid Sans Mono Slashed for Powerline
    Droid Sans Mono Dotted for Powerline
    Inconsolata for Powerline
    Inconsolata-dz for Powerline
    Inconsolata-g for Powerline
    Literation Mono Powerline
    Meslo for Powerline
    Roboto for Powerline
    Sauce Code Powerline
    Symbol Neu Powerline
    Terminess Powerline
    Tinos Powerline
    Fura Powerline
install    : |
    # Remove fonts with non-SPDX licenses
    rm -r UbuntuMono Monofur DejaVuSansMono Hack
    # Remove un-needed items
    rm -r install.sh install.ps1 samples
    mkdir -p %installroot%/usr/share/fonts/powerline
    cp -r * %installroot%/usr/share/fonts/powerline
